services:
  - type: web
    name: demo
    runtime: node
    plan: free
    buildCommand: ./scripts/build.sh
    startCommand: ./scripts/start.sh
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: GROK_API_KEY
        sync: false
      - key: NEXT_PUBLIC_VAPI_PUBLIC_KEY
        sync: false
      - key: VAPI_PRIVATE_KEY
        sync: false
      - key: VAPI_ASSISTANT_ID
        sync: false
      - key: SERPER_API_KEY
        sync: false
