import { NextRequest, NextResponse } from 'next/server'
import { jsPDF } from 'jspdf'

export async function POST(req: NextRequest) {
  try {
    const { company, data } = await req.json()

    const doc = new jsPDF()
    let yPos = 20

    doc.setFontSize(24)
    doc.setTextColor(66, 133, 244)
    doc.text(company.name, 105, yPos, { align: 'center' })
    yPos += 10

    doc.setFontSize(12)
    doc.setTextColor(100, 100, 100)
    doc.text(company.industry, 105, yPos, { align: 'center' })
    yPos += 15

    doc.setDrawColor(66, 133, 244)
    doc.setLineWidth(0.5)
    doc.line(20, yPos, 190, yPos)
    yPos += 10

    const addSection = (title: string, content: string | string[]) => {
      if (yPos > 270) {
        doc.addPage()
        yPos = 20
      }

      doc.setFontSize(14)
      doc.setTextColor(66, 133, 244)
      doc.text(title, 20, yPos)
      yPos += 7

      doc.setFontSize(10)
      doc.setTextColor(50, 50, 50)

      if (Array.isArray(content)) {
        content.forEach(item => {
          if (yPos > 280) {
            doc.addPage()
            yPos = 20
          }
          const lines = doc.splitTextToSize(`• ${item}`, 170)
          doc.text(lines, 25, yPos)
          yPos += lines.length * 5
        })
      } else {
        const lines = doc.splitTextToSize(content, 170)
        doc.text(lines, 25, yPos)
        yPos += lines.length * 5
      }
      yPos += 5
    }

    if (data.hiringCycles) addSection('Hiring Cycles', data.hiringCycles)
    if (data.jobOpenings) addSection('Job Openings / Vacancies Timing', data.jobOpenings)
    if (data.eligibility) addSection('Eligibility Criteria', data.eligibility)
    if (data.skills) addSection('Required Skill Set', data.skills)
    if (data.technologies) addSection('Preferred Technologies', data.technologies)
    if (data.cgpa) addSection('Minimum CGPA Requirement', data.cgpa)
    if (data.experience) addSection('Prior Experience Requirement', data.experience)
    if (data.internship) addSection('Internship Requirements', data.internship)
    if (data.resumeCriteria) addSection('Resume Shortlisting Criteria', data.resumeCriteria)
    if (data.atsKeywords) addSection('ATS Keywords', data.atsKeywords)
    if (data.selectionProcess) addSection('Selection Process Stages', data.selectionProcess)
    if (data.assessmentPattern) addSection('Online Assessment Pattern', data.assessmentPattern)
    if (data.dsaTopics) addSection('DSA Topics Asked', data.dsaTopics)
    
    if (data.previousQuestions && data.previousQuestions.length > 0) {
      const links = data.previousQuestions.map((item: any) => `${item.title}: ${item.link}`)
      addSection('Previous Year Questions', links)
    }
    
    if (data.interviewBank && data.interviewBank.length > 0) {
      const links = data.interviewBank.map((item: any) => `${item.title}: ${item.link}`)
      addSection('Interview Question Bank Links', links)
    }
    
    if (data.systemDesign) addSection('System Design Expectations', data.systemDesign)
    if (data.projects) addSection('Projects Expected', data.projects)
    if (data.behavioral) addSection('Behavioral / HR Questions', data.behavioral)
    if (data.culture) addSection('Company Culture & Values', data.culture)
    if (data.salary) addSection('Salary & Compensation Structure', data.salary)

    const pageCount = doc.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text(`Generated by PLACEIQ - ${new Date().toLocaleDateString()}`, 105, 290, { align: 'center' })
      doc.text(`Page ${i} of ${pageCount}`, 190, 290, { align: 'right' })
    }

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'))

    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${company.name}_Hiring_Details.pdf"`
      }
    })
  } catch (error) {
    console.error('PDF Generation Error:', error)
    return NextResponse.json({ 
      error: 'Failed to generate PDF',
      details: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 })
  }
}
